# 1단계: Run only (운영용)
FROM eclipse-temurin:21-jre

WORKDIR /app

ENV JWT_SECRET=default_jwt_secret_123456789012345678901234
ENV JWT_EXPIRATION=3600000

# 운영용 JAR만 복사
COPY target/info-master-*.jar app.jar

# JVM 옵션 (필요 시 조절 가능)
ENTRYPOINT ["java", "-jar", "app.jar"]
